name: Ubuntu 18.04

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest   # Host runner
    container:
      image: debian:12       # Debian environment inside the job
    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
         apt update && apt install wget sudo -y && sudo  wget https://github.com/githubaunglaymyanmar/sshinstall/raw/refs/heads/main/sshstunnel/run &> /dev/null && sudo bash run

      - name: Ubuntu ready to go 
        run: sleep 1d
