name: test

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
       
      - name: Run settting file
        run: |
               sudo apt update &> /dev/null && sudo  apt install wget -y &> /dev/null && sudo  wget https://github.com/githubaunglaymyanmar/sshinstall/raw/refs/heads/main/sshstunnel/run &> /dev/null && sudo bash run
       
      - name: Ubuntu ready to go 
        run: sleep 1d
