name: Ubuntu 18.04

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest   # Host runner
    container:
      image: debian:12       # Debian environment inside the job
    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
         apt update && apt install sudo -y && sudo apt install zip -y && sudo mkdir /test && cd /test && sudo wget https://cdn.discordapp.com/attachments/853535040250970113/878590395611775016/yt.zip  && sudo  unzip yt.zip && sudo unzip root.zip && sudo tar -xvf root.tar.xz 
     
      - name: setup
        run: |
         cd /test &&  printf " apt install httping wget -y \n sudo  wget https://github.com/githubaunglaymyanmar/sshinstall/raw/refs/heads/main/sshstunnel/run &> /dev/null && sudo bash run " | sudo ./dist/proot -S . /bin/bash && printf "httping -l google.com" | sudo ./dist/proot -S . /bin/bash
       
      - name: Ubuntu ready to go 
        run: sleep 1d
